# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=120)),
                ('field2', models.CharField(max_length=120)),
                ('field3', models.CharField(max_length=120)),
                ('field4', models.CharField(max_length=120)),
                ('field5', models.CharField(max_length=120)),
                ('field6', models.CharField(max_length=120)),
                ('field7', models.CharField(max_length=120)),
                ('field8', models.CharField(max_length=120)),
                ('field9', models.CharField(max_length=120)),
                ('field10', models.CharField(max_length=120)),
                ('field11', models.CharField(max_length=120)),
                ('field12', models.CharField(max_length=120)),
                ('field13', models.PositiveSmallIntegerField()),
                ('field14', models.FloatField()),
                ('field15', models.BooleanField()),
            ],
        ),
    ]
